HOST_BUILDDIR	= build/host/
OBJ2C		= $(HOST_BUILDDIR)obj2c
BUILDDIR	= build/
ALL		= $(BUILDDIR)cube.h \
			$(BUILDDIR)modern.h \
			$(BUILDDIR)rat.h \
			$(BUILDDIR)rat_lofi.h \
			$(BUILDDIR)teapot.h  \
			$(BUILDDIR)torus.h

.PHONY: all clean $(OBJ2C)

all: $(ALL)

clean:
	rm -f $(ALL)

$(OBJ2C):
	$(MAKE) -f Makefile.host $(@)

$(BUILDDIR):
	mkdir -p $(@)

$(BUILDDIR)%.h: MODEL_NAME = $(@:$(BUILDDIR)%.h=%)
$(BUILDDIR)%.h: res/%.obj $(OBJ2C) | $(BUILDDIR)
	$(OBJ2C) $(<) $(MODEL_NAME) >$(@)
